<?php
/**
 * @var $this Mage_Core_Block_Template
 */
?>

<div class="mm-review">
    <div id="container">
        <section id="page-title">
            <h2><?php echo $this->getHelper()->langReviewProduct(); ?></h2>
            <p class="section-paragraph">
                <span class="mm-loading">
                    <?php echo $this->getHelper()->langSubmittingReview(); ?>
                </span>
                <span class="mm-error" style="display: none;">
                    <?php echo $this->getHelper()->langThereWasProblem(); ?> <span class="error-message"></span>
                </span>
                <span class="mm-complete" style="display: none;">
                    <?php echo $this->getHelper()->langThanksReviewComplete(); ?>
                </span>
            </p>
        </section>
    </div>
</div>

<script>
    MageMailData = typeof(MageMailData) != 'undefined' ? MageMailData : {};
    MageMailData.review_data = <?php echo json_encode($this->getPost()); ?>;
</script>