<?php
/**
 * @var $this Mage_Core_Block_Template
 */
?>

<div class="unsubscribe">

    <div id="container">
        <section id="page-title">
            <h2 class='clean'><?php echo __("You've Been Unsubscribed");?></h2>
            <p class="section-paragraph"><?php echo __("The email address %s has been unsubscribed.", htmlspecialchars($this->getMmRecipient()));?></p>
        </section>
    </div>
</div>