<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Finder
 */
?>
<?php
/**
 * Copyright © 2015 Amasty. All rights reserved.
 */
/**
 * @var $block \Amasty\Finder\Block\Form
 */
?>
<?php $finderId = 'amfinder_' . $block->getFinder()->getId(); ?>
<div class="amfinder-<?= $block->getFinder()->getTemplate() ?>" id="<?= $finderId ?>"
     location="<?= $block->getLocation() ?>">
    <form method="post" action="<?= $block->getActionUrl() ?>">
        <input type="hidden" name="finder_id" value="<?= $block->getId() ?>"/>
        <input type="hidden" name="back_url" value="<?= $block->getBackUrl() ?>"/>
        <input type="hidden" name="reset_url" value="<?= $block->getResetUrl() ?>"/>
        <input type="hidden" name="category_id" value="<?= $block->getCurrentCategoryId() ?>"/>
        <input type="hidden" name="current_apply_url"
               value="<?= $block->escapeUrl($block->getCurrentApplyUrlEncoded()) ?>"/>
        <div class="amfinder-title">
            <span><?= $block->escapeHtml($block->getFinder()->getName()) ?></span>
        </div>
        <ul class="amfinder-toggle">
            <?php foreach ($block->getFinder()->getDropdowns() as $dropdown) : ?>
                <li style="width: <?= $block->getDropdownWidth() ?>%">
                    <div class="dropdown-title"><?= __($block->escapeHtml($dropdown->getName())) ?></div>
                    <div class="dropdown-element amshopby-clearer">
                        <select <?= $block->getDropdownAttributes($dropdown) ?>>
                            <?php foreach ($block->getDropdownValues($dropdown) as $v) : ?>
                                <option value="<?= $v['value'] ?>"
                                    <?php if ($v['selected']) : ?>
                                        selected="selected"
                                    <?php endif ?> >
                                    <?= $block->escapeHtml($v['label']) ?>
                                </option>
                            <?php endforeach ?>
                        </select>
                    </div>
                </li>
            <?php endforeach ?>
            <li class="last">
                <div class="amfinder-buttons <?= ($block->isButtonsVisible() ? '' : 'no-display') ?>">
                    <button class="button action primary" title="<?= __('Find') ?>"
                            type="submit"><span><span><?= __('Find') ?></span></span></button>
                    <button class="button" name="reset" value="1" title="<?= __('Reset') ?>"
                            type="submit"><span><span><?= __('Reset') ?></span></span></button>
                </div>
            </li>
        </ul>
    </form>
</div>
<script type="text/javascript">
    require(['jquery', 'Amasty_Finder/js/amfinder'], function ($) {
        var finderConfig = <?= $block->getJsonConfig(); ?>;
        finderConfig.containerId = '<?= $finderId ?>';
        finderConfig.loadingText = '<?= __('Loading...')?>';
        $("#" + finderConfig.containerId).amfinder(finderConfig);

        $('#' + finderConfig.containerId + ' .amfinder-title').on('click', function () {
            var block = $(this).parent();
            block.toggleClass('open');
        });
    });
</script>
<br/>
